apiVersion: v1
kind: Secret
metadata:
  name: basic-docker-user-pass
  annotations:
    tekton.dev/docker-0: https://registry.cn-hangzhou.aliyuncs.com
type: kubernetes.io/basic-auth
stringData:
  username: hobo@hbchen.com
  password: 123456
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: build-bot
secrets:
  - name: basic-docker-user-pass
