---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
#  name: grpc-gateway-pipeline-run
  generateName: grpc-gateway-pipeline-run-
spec:
  serviceAccountName: build-bot
  pipelineRef:
    name: grpc-gateway-pipeline
  params:
    - name: url
      value: https://github.com/hb-chen/gateway
    - name: revision
      value: master
  workspaces:
    - name: shared-workspace
      persistentvolumeclaim:
        claimName: golang-source-pvc
    - name: dockerconfig
      secret:
        secretName: dockerconfig
    - name: kubeconfig
      secret:
        secretName: k8s-kubeconfig
