apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: helm-kubectl-deploy
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: helm, kubectl
    tekton.dev/displayName: helm-kubectl-deploy
spec:
  description: >-
    Use kubectl and helm deploy application
  params:
    - name: image
      default: dtzar/helm-kubectl:3.4.2
      description: kubectl and helm image
    - name: kubeconfig
      default: k8s-kubeconfig
      description: kubernetes cluster kubeconfig
    - name: commands
      default: kubectl version
  workspaces:
    - name: source
  results:
  steps:
    - name: helm-kubectl-deploy
      image: $(params.image)
      workingDir: $(workspaces.source.path)
      script: |
        pwd
        ls -l
        $(params.commands)
      volumeMounts:
        - name: kubeconfig
          mountPath: "/tekton/home/.kube"
          readOnly: true
  volumes:
    - name: kubeconfig
      secret:
        secretName: $(params.kubeconfig)
