---
# Kubernetes
# kubectl create secret generic k8s-kubeconfig --from-file=$HOME/.kube/config
apiVersion: v1
kind: Secret
metadata:
  name: k8s-kubeconfig
type: Opaque
data:
  config: {$HOME/.kube/config base64 encode}
